In [11]:
import numpy as np

In [12]:
a=np.array([[1,2,3,4,5],[1,213,123,1,1]])

In [13]:
a

array([[  1,   2,   3,   4,   5],
       [  1, 213, 123,   1,   1]])

In [14]:
a.size

10

In [15]:
a.shape

(2, 5)

In [16]:
b=np.arange(1,10,2)

In [17]:
b

array([1, 3, 5, 7, 9])

In [18]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [21]:
np.linspace(0,19,5)

array([ 0.  ,  4.75,  9.5 , 14.25, 19.  ])

In [22]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.randn(8)

array([-2.63587729,  0.91345391,  1.90417705,  0.77789792, -0.74922439,
       -0.82151446, -0.57446531, -0.67144331])

In [24]:
np.random.randn(3,3)

array([[-0.09712076,  0.15170343, -0.65932612],
       [ 0.47378767, -0.09991094, -1.07233241],
       [-1.14327542, -0.87093835,  1.93228985]])

In [25]:
np.random.randint(1,10)

2

In [26]:
np.random.randint(1,20,3)

array([ 4,  5, 19])

In [27]:
dizi=np.random.randint(1,100,30)
dizi.size

30

In [28]:
dizi.reshape(3,10)

array([[62,  3, 94, 55, 30, 18, 16, 76, 16, 94],
       [65, 34, 13, 44, 94, 36,  9, 66, 16, 71],
       [ 9, 23,  2,  7, 78, 54, 38, 27, 23, 11]])

In [29]:
dizi.resize(5,6)
dizi

array([[62,  3, 94, 55, 30, 18],
       [16, 76, 16, 94, 65, 34],
       [13, 44, 94, 36,  9, 66],
       [16, 71,  9, 23,  2,  7],
       [78, 54, 38, 27, 23, 11]])

In [30]:
dizi.max()

94

In [31]:
dizi.argmax()

2

In [32]:
dizi.argmin()

22

In [33]:
dizi

array([[62,  3, 94, 55, 30, 18],
       [16, 76, 16, 94, 65, 34],
       [13, 44, 94, 36,  9, 66],
       [16, 71,  9, 23,  2,  7],
       [78, 54, 38, 27, 23, 11]])

In [34]:
dizi.sort()

In [35]:
dizi

array([[ 3, 18, 30, 55, 62, 94],
       [16, 16, 34, 65, 76, 94],
       [ 9, 13, 36, 44, 66, 94],
       [ 2,  7,  9, 16, 23, 71],
       [11, 23, 27, 38, 54, 78]])

In [36]:
benimdizim=np.arange(0,10)

In [37]:
benimdizim[3:8]=-5

In [38]:
benimdizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9])

In [39]:
ornekdizi=np.arange(0,20)

In [40]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
ornekdizikopya=ornekdizi.copy()

In [42]:
ornekdizikopya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
ornekdizikopya[2:4]=700
ornekdizikopya

array([  0,   1, 700, 700,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [44]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
yeniliste=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]

In [46]:
type(yeniliste)

list

In [47]:
matris=np.array(yeniliste)


In [48]:
type(matris)

numpy.ndarray

In [49]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [50]:
matris[0,1]

2

In [51]:
matris[[0,1]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
yenibirdizi=np.random.randint(0,20,20)

In [53]:
yenibirdizi

array([17, 17,  1, 19,  2, 19,  5,  6, 13, 16, 17, 15,  7,  7,  4, 17,  6,
       17, 16, 15])

In [54]:
yenibirdizi>10

array([ True,  True, False,  True, False,  True, False, False,  True,
        True,  True,  True, False, False, False,  True, False,  True,
        True,  True])

In [55]:
sonucdizisi=yenibirdizi>15

In [56]:
sonucdizisi

array([ True,  True, False,  True, False,  True, False, False, False,
        True,  True, False, False, False, False,  True, False,  True,
        True, False])

In [57]:
yenibirdizi[sonucdizisi]

array([17, 17, 19, 19, 16, 17, 17, 17, 16])

In [58]:
yenibirdizi[yenibirdizi>10]

array([17, 17, 19, 19, 13, 16, 17, 15, 17, 17, 16, 15])

# pandas

In [59]:
import pandas as pd

In [60]:
benimsozlugum={"Ali":50,"Veli":40,"Osman":20}

In [61]:
pd.Series(benimsozlugum)

Ali      50
Veli     40
Osman    20
dtype: int64

In [62]:
pd.Series(["Hüseyin","Uyanik","Ahmet"],[3,5,6])

3    Hüseyin
5     Uyanik
6      Ahmet
dtype: object

In [63]:
benimsozlugum["Ali"]

50

In [69]:
q=np.random.randn(4,3)
q

array([[ 0.26373552,  1.4154558 , -0.70492082],
       [-1.25201335, -0.68744609, -0.52121929],
       [ 0.02911656, -0.8919372 , -0.4156713 ],
       [ 0.7373829 ,  0.17055486, -0.55859224]])

In [70]:
df=pd.DataFrame(q)

In [71]:
df

0         1         2
0  0.263736  1.415456 -0.704921
1 -1.252013 -0.687446 -0.521219
2  0.029117 -0.891937 -0.415671
3  0.737383  0.170555 -0.558592

In [72]:
df[0]

0    0.263736
1   -1.252013
2    0.029117
3    0.737383
Name: 0, dtype: float64

In [106]:
yenidataframe=pd.DataFrame(q,index=["Ali","Veli","osman","macit"],columns=[1,2,3])

In [107]:
yenidataframe

1         2         3
Ali    0.263736  1.415456 -0.704921
Veli  -1.252013 -0.687446 -0.521219
osman  0.029117 -0.891937 -0.415671
macit  0.737383  0.170555 -0.558592

In [108]:
yenidataframe[[2,3]]

2         3
Ali    1.415456 -0.704921
Veli  -0.687446 -0.521219
osman -0.891937 -0.415671
macit  0.170555 -0.558592

In [109]:
yenidataframe.loc["Veli"]

1   -1.252013
2   -0.687446
3   -0.521219
Name: Veli, dtype: float64

In [110]:
yenidataframe.iloc[3]

1    0.737383
2    0.170555
3   -0.558592
Name: macit, dtype: float64

In [111]:
yenidataframe.drop([2],axis=1)

1         3
Ali    0.263736 -0.704921
Veli  -1.252013 -0.521219
osman  0.029117 -0.415671
macit  0.737383 -0.558592

In [112]:
yenidataframe   # tamamen silmek icin inplace=True yapılır

1         2         3
Ali    0.263736  1.415456 -0.704921
Veli  -1.252013 -0.687446 -0.521219
osman  0.029117 -0.891937 -0.415671
macit  0.737383  0.170555 -0.558592

In [113]:
yenidataframe.drop([2],axis=1, inplace=True)

In [114]:
yenidataframe

1         3
Ali    0.263736 -0.704921
Veli  -1.252013 -0.521219
osman  0.029117 -0.415671
macit  0.737383 -0.558592

In [115]:
yenidataframe.loc["Ali"][1]

0.2637355226148305

In [131]:
yenidataframe

1         3
Yeni_index                    
hus         0.263736 -0.704921
semra      -1.252013 -0.521219
dilek       0.029117 -0.415671
sare        0.737383 -0.558592

In [132]:
yeniindexlistesi=["hus","semra","dilek","sare"]

In [133]:
yenidataframe["Yeni_index"]=yeniindexlistesi

In [134]:
yenidataframe

1         3 Yeni_index
Yeni_index                               
hus         0.263736 -0.704921        hus
semra      -1.252013 -0.521219      semra
dilek       0.029117 -0.415671      dilek
sare        0.737383 -0.558592       sare

In [135]:
yenidataframe.set_index("Yeni_index",inplace=True)

In [136]:
yenidataframe

1         3
Yeni_index                    
hus         0.263736 -0.704921
semra      -1.252013 -0.521219
dilek       0.029117 -0.415671
sare        0.737383 -0.558592

In [137]:
yenidataframe.loc["hus"]

1    0.263736
3   -0.704921
Name: hus, dtype: float64

In [138]:
ilkindex=["Simpson","Simpson","Simpson","Southpark","Southpark","Southpark"]
icindex=["homer","bart","marge","Cartman","Kenny","Kyle"]

# MULTI INDEX

In [139]:
birlesmisindex=list(zip(ilkindex,icindex))

In [140]:
birlesmisindex

[('Simpson', 'homer'),
 ('Simpson', 'bart'),
 ('Simpson', 'marge'),
 ('Southpark', 'Cartman'),
 ('Southpark', 'Kenny'),
 ('Southpark', 'Kyle')]

In [142]:
birlesmisindex=pd.MultiIndex.from_tuples(birlesmisindex)

In [143]:
birlesmisindex

MultiIndex([(  'Simpson',   'homer'),
            (  'Simpson',    'bart'),
            (  'Simpson',   'marge'),
            ('Southpark', 'Cartman'),
            ('Southpark',   'Kenny'),
            ('Southpark',    'Kyle')],
           )

In [146]:
type(birlesmisindex)

pandas.core.indexes.multi.MultiIndex

In [147]:
cizgifilmlistesi=[[40,"A"],[10,"B"],[30,"C"],[9,"D"],[10,"E"],[11,"F"]]

In [148]:
cizgifilmlistesi_df=pd.DataFrame(cizgifilmlistesi, index=birlesmisindex , columns=["yas","meslek"])

In [149]:
cizgifilmlistesi_df

yas meslek
Simpson   homer     40      A
          bart      10      B
          marge     30      C
Southpark Cartman    9      D
          Kenny     10      E
          Kyle      11      F

In [150]:
cizgifilmlistesi_df.loc["Simpson"]

yas meslek
homer   40      A
bart    10      B
marge   30      C

In [157]:
cizgifilmlistesi_df.loc["Simpson"].iloc[0]

yas       40
meslek     A
Name: homer, dtype: object

In [159]:
cizgifilmlistesi_df.loc["Simpson"].loc["bart"]

yas       10
meslek     B
Name: bart, dtype: object

# MISSING VALUES

In [166]:
sozlukverisi={"istanbul":[25,28,np.nan],"izmir":[np.nan,21,43],"manisa":[np.nan,22,21]}

In [167]:
df_havadurumu=pd.DataFrame(sozlukverisi)

In [168]:
df_havadurumu

istanbul  izmir  manisa
0      25.0    NaN     NaN
1      28.0   21.0    22.0
2       NaN   43.0    21.0

In [171]:
df_havadurumu.dropna()

istanbul  izmir  manisa
1      28.0   21.0    22.0

In [172]:
df_havadurumu.fillna(23)

istanbul  izmir  manisa
0      25.0   23.0    23.0
1      28.0   21.0    22.0
2      23.0   43.0    21.0

In [175]:
sozlukverisi2={"istanbul":[25,28,np.nan],"izmir":[np.nan,21,43],"manisa":[np.nan,22,21],
               "antalya":[np.nan,np.nan,34]}

In [177]:
df_havadurumu2=pd.DataFrame(sozlukverisi2)

In [179]:
df_havadurumu2.dropna(axis=1,thresh=2)

istanbul  izmir  manisa
0      25.0    NaN     NaN
1      28.0   21.0    22.0
2       NaN   43.0    21.0

In [180]:
sozlukverisi3={"istanbul":[25,28,np.nan],"izmir":[np.nan,21,43],"manisa":[np.nan,22,21],
               "antalya":[np.nan,np.nan,34]}

In [181]:
df_havadurumu3=pd.DataFrame(sozlukverisi3)

In [186]:
df_havadurumu3.fillna(df_havadurumu3.mean())

istanbul  izmir  manisa  antalya
0      25.0   32.0    21.5     34.0
1      28.0   21.0    22.0     34.0
2      26.5   43.0    21.0     34.0

# GROUP BY

In [4]:
import pandas as pd
import numpy as np

In [9]:
maas_sozlugu={"Departmanlar":["Finans","Finans","Yazılım","Yazılım","IK","Hukuk"],
             "Çalışan isimleri":["Ahmet","Mehmet","Hüseyin","Sare","Zeynep","Burak"],
             "Maas":[4000,5000,5000,10000,6000,7500]}

In [10]:
maas_sozlugu

{'Departmanlar': ['Finans', 'Finans', 'Yazılım', 'Yazılım', 'IK', 'Hukuk'],
 'Çalışan isimleri': ['Ahmet', 'Mehmet', 'Hüseyin', 'Sare', 'Zeynep', 'Burak'],
 'Maas': [4000, 5000, 5000, 10000, 6000, 7500]}

In [11]:
maas_sozlugu_df=pd.DataFrame(maas_sozlugu)

In [12]:
maas_sozlugu_df

Departmanlar Çalışan isimleri   Maas
0       Finans            Ahmet   4000
1       Finans           Mehmet   5000
2      Yazılım          Hüseyin   5000
3      Yazılım             Sare  10000
4           IK           Zeynep   6000
5        Hukuk            Burak   7500

In [19]:
grup=maas_sozlugu_df.groupby("Departmanlar")

In [22]:
grup.count()

Çalışan isimleri  Maas
Departmanlar                        
Finans                       2     2
Hukuk                        1     1
IK                           1     1
Yazılım                      2     2

In [23]:
grup.mean()

Maas
Departmanlar        
Finans        4500.0
Hukuk         7500.0
IK            6000.0
Yazılım       7500.0

In [29]:
grup.describe()


Maas                                                       \
             count    mean          std     min     25%     50%     75%   
Departmanlar                                                              
Finans         2.0  4500.0   707.106781  4000.0  4250.0  4500.0  4750.0   
Hukuk          1.0  7500.0          NaN  7500.0  7500.0  7500.0  7500.0   
IK             1.0  6000.0          NaN  6000.0  6000.0  6000.0  6000.0   
Yazılım        2.0  7500.0  3535.533906  5000.0  6250.0  7500.0  8750.0   

                       
                  max  
Departmanlar           
Finans         5000.0  
Hukuk          7500.0  
IK             6000.0  
Yazılım       10000.0

# merging (kaynastırma)

In [30]:
mergesozluk1={"isimler":["Ali","Veli","Osman","Haydar"], "Spor":["Yuzme","Futbol","Basketbol","Tenis"],}
mergesozluk2={"isimler":["Ali","Veli","Osman","Haydar"], "Kalori":[100,200,150,170]}

In [31]:
merge_df1=pd.DataFrame(mergesozluk1)
merge_df1

isimler       Spor
0     Ali      Yuzme
1    Veli     Futbol
2   Osman  Basketbol
3  Haydar      Tenis

In [32]:
merge_df2=pd.DataFrame(mergesozluk2)
merge_df2

isimler  Kalori
0     Ali     100
1    Veli     200
2   Osman     150
3  Haydar     170

In [36]:
pd.merge(merge_df1,merge_df2, on="isimler")

isimler       Spor  Kalori
0     Ali      Yuzme     100
1    Veli     Futbol     200
2   Osman  Basketbol     150
3  Haydar      Tenis     170

In [37]:
maas={"isimler":["Hüseyin","Zeynep","Sare","Burak"],
      "Departman":["Yazılım","Satış","Pazarlama","Yazılım"],
     "Maas":[200,300,400,500]}

In [38]:
maas_df=pd.DataFrame(maas)

In [39]:
maas_df

isimler  Departman  Maas
0  Hüseyin    Yazılım   200
1   Zeynep      Satış   300
2     Sare  Pazarlama   400
3    Burak    Yazılım   500

In [41]:
maas_df["Departman"].unique()

array(['Yazılım', 'Satış', 'Pazarlama'], dtype=object)

In [42]:
maas_df["Departman"].nunique()

3

In [43]:
maas_df["Departman"].value_counts()

Yazılım      2
Satış        1
Pazarlama    1
Name: Departman, dtype: int64